logging:
  level:
    org.springframework.web: WARN
    com.cesarmando.website: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} \n\t %msg%n"
server:
  error:
    path: /error
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"