logging:
  level:
    org.springframework.web: INFO
    com.cesarmando.website: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"